version: '3.1'
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    hostname: "hsdconnect-db-dev"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "hsdconnect-user"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    hostname: "hsdconnect-db-web-dev"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "hsdconnect-user"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "secret"
